<a href="https://colab.research.google.com/github/JakeOh/202110_itw_lab_python/blob/main/ml01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

필요한 라이브러리 모듈 임포트

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# np.ndarray 클래스 속성들(properties)

In [2]:
# 모든 원소가 1.0으로 이루어진 (3, 4) 모양의 2차원 배열 생성
array = np.ones((3, 4))

In [3]:
print(array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [4]:
type(array)

numpy.ndarray

In [5]:
array.dtype  # 배열의 원소의 데이터 타입

dtype('float64')

In [6]:
array.shape  # 배열의 각 축(axis)를 따라서 있는 원소들의 개수로 만들어진 tuple

(3, 4)

In [7]:
array.size  # 배열의 모든 원소들의 개수

12

In [8]:
array.ndim  # 배열의 차원의 개수(number of dimension). 배열의 축(axis)의 개수.

2

In [9]:
# [1, 6) 범위의 정수들로 이루어진 1차원 배열
array = np.arange(1, 6)
print(array)

[1 2 3 4 5]


In [10]:
print('dtype:', array.dtype)
print('shape:', array.shape)
print('size:', array.size)
print('ndim:', array.ndim)

dtype: int64
shape: (5,)
size: 5
ndim: 1


In [12]:
# [1, 25) 범위의 정수들로 이루어진 (2, 3, 4) shape의 3차원 배열
array = np.arange(1, 25).reshape((2, 3, 4))
print(array)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [13]:
print('dtype:', array.dtype)
print('shape:', array.shape)
print('size:', array.size)
print('ndim:', array.ndim)

dtype: int64
shape: (2, 3, 4)
size: 24
ndim: 3


np.ndarray의 indexing

* Python list 인덱스 사용 방법: `list[i][j][k]...`
* numpy ndarray 인덱스 사용 방법:
    * `array[i][j][k]...`
    * `array[i, j, k, ...]`


In [14]:
print(array)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [15]:
print(array[0])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
print(array[0][1])

[5 6 7 8]


In [17]:
print(array[0, 1])

[5 6 7 8]


In [18]:
print(array[0][1][2])

7


In [19]:
print(array[0, 1, 2])

7
